services:
  dataprocessorservice:
    image: ${DOCKER_REGISTRY-}dataprocessorservice
    build:
      context: .
      dockerfile: DataProcessorService/Dockerfile

  fileparserservice:
    image: ${DOCKER_REGISTRY-}fileparserservice
    build:
      context: .
      dockerfile: FileParserService/Dockerfile
    volumes:
      - data:/home/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data: